services:
  - type: web
    name: quantum-safe-explorer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    branch: main
    envVars:
      - key: NEXT_PUBLIC_PQC_ENABLED
        value: "true"
      - key: PQC_LEVEL
        value: "FIPS-203-ML-KEM-1024"
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: quantum-safe-explorer
          type: web
          property: host
      - key: AUTH_GITHUB_ID
        sync: false
      - key: AUTH_GITHUB_SECRET
        sync: false
